# Generated by Django 5.2.7 on 2025-10-05 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDoctorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Any special notes about this patient-doctor assignment')),
                ('is_active', models.BooleanField(default=True, help_text='Set to False if patient is no longer seeing this doctor')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mappings_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_mappings', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_mappings', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Patient-Doctor Mapping',
                'verbose_name_plural': 'Patient-Doctor Mappings',
                'db_table': 'patient_doctor_mappings',
                'ordering': ['-assigned_date'],
                'indexes': [models.Index(fields=['patient', 'doctor'], name='patient_doc_patient_68e979_idx'), models.Index(fields=['assigned_date'], name='patient_doc_assigne_ddfdfc_idx')],
                'unique_together': {('patient', 'doctor')},
            },
        ),
    ]
