# Generated by Django 5.2.7 on 2025-10-05 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('specialization', models.CharField(help_text='e.g., Cardiologist, Neurologist, General Physician', max_length=100)),
                ('qualification', models.CharField(help_text='e.g., MBBS, MD, MS', max_length=255)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('clinic_address', models.TextField()),
                ('consultation_fee', models.DecimalField(decimal_places=2, help_text='Consultation fee in your currency', max_digits=10)),
                ('is_available', models.BooleanField(default=True, help_text='Is the doctor currently accepting patients?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'db_table': 'doctors',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['email'], name='doctors_email_ac323b_idx'), models.Index(fields=['specialization'], name='doctors_special_6661e0_idx'), models.Index(fields=['is_available'], name='doctors_is_avai_62f7a8_idx')],
            },
        ),
    ]
